linters:
  enable:
    - govet
    - staticcheck
    - gofmt
  disable:
    - errcheck

linters-settings:
  gofmt:
    simplify: true  # Включает упрощение кода, которое предоставляет gofmt
  staticcheck:
    checks: ["all"]  # Запускает все проверки staticcheck